"""add cipc_ar_fees reference table

Revision ID: 0629a686b680
Revises: 4bdfb0e9e6a2
Create Date: 2026-06-09 15:43:46.804543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0629a686b680'
down_revision = '4bdfb0e9e6a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    cipc_ar_fees = op.create_table('cipc_ar_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_class', sa.String(length=16), nullable=False),
    sa.Column('turnover_lower', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('turnover_upper', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fee_on_time', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fee_late', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.CheckConstraint("entity_class IN ('company', 'cc')", name='ck_cipc_ar_fees_entity_class'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cipc_ar_fees_class_lower', 'cipc_ar_fees', ['entity_class', 'turnover_lower'], unique=False)
    # ### end Alembic commands ###

    # Seed the bands from the single source of truth shared with the test fixtures (so
    # they cannot drift). Half-open [turnover_lower, turnover_upper): lower inclusive,
    # upper exclusive; NULL upper = open-ended top band. (fee_late was NULL when this
    # migration was first written; migration 7c1e0a9b4f23 later back-filled it, and
    # CIPC_AR_FEE_SEED now derives it — see that seed for the note.)
    from app.models.cipc_ar_fee import CIPC_AR_FEE_SEED

    op.bulk_insert(cipc_ar_fees, CIPC_AR_FEE_SEED)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cipc_ar_fees_class_lower', table_name='cipc_ar_fees')
    op.drop_table('cipc_ar_fees')
    # ### end Alembic commands ###
