"""Add staff table and assignee_id FK on obligation_instances

Revision ID: 1009fb776132
Revises: 6bee3e81960c
Create Date: 2026-05-13 07:54:03.525115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1009fb776132'
down_revision = '6bee3e81960c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Enum('TAX', 'SECRETARIAL', 'BOTH', name='staffrole'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('obligation_instances', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_obligation_instances_assignee_id'), 'obligation_instances', ['assignee_id'], unique=False)
    op.create_foreign_key(None, 'obligation_instances', 'staff', ['assignee_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'obligation_instances', type_='foreignkey')
    op.drop_index(op.f('ix_obligation_instances_assignee_id'), table_name='obligation_instances')
    op.drop_column('obligation_instances', 'assignee_id')
    op.drop_table('staff')
    # ### end Alembic commands ###
