"""add client contact fields

Revision ID: 1f1ec8ef2984
Revises: 6b03e634f495
Create Date: 2026-06-03 09:55:53.327074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1ec8ef2984'
down_revision = '6b03e634f495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('contact_person', sa.String(length=200), nullable=True))
    op.add_column('clients', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('mobile', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('email', sa.String(length=200), nullable=True))
    op.add_column('clients', sa.Column('physical_address', sa.Text(), nullable=True))
    op.add_column('clients', sa.Column('postal_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'postal_address')
    op.drop_column('clients', 'physical_address')
    op.drop_column('clients', 'email')
    op.drop_column('clients', 'mobile')
    op.drop_column('clients', 'phone')
    op.drop_column('clients', 'contact_person')
    # ### end Alembic commands ###
