"""add cipc_annual_instances table

Revision ID: 339f270f74bb
Revises: c85ae4195437
Create Date: 2026-06-09 13:09:16.366299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339f270f74bb'
down_revision = 'c85ae4195437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cipc_annual_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('anniversary_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('GENERATED', 'INVOICED', 'INVOICE_PAID', 'BO_SUBMITTED', 'AR_SUBMITTED', 'CLOSED', name='cipcannualstatus'), nullable=False),
    sa.Column('annual_turnover_cents', sa.BigInteger(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'anniversary_date', name='uq_cipc_annual_instances_client_anniversary')
    )
    op.create_index(op.f('ix_cipc_annual_instances_assignee_id'), 'cipc_annual_instances', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_cipc_annual_instances_client_id'), 'cipc_annual_instances', ['client_id'], unique=False)
    op.create_index('ix_cipc_annual_instances_status_due', 'cipc_annual_instances', ['status', 'due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cipc_annual_instances_status_due', table_name='cipc_annual_instances')
    op.drop_index(op.f('ix_cipc_annual_instances_client_id'), table_name='cipc_annual_instances')
    op.drop_index(op.f('ix_cipc_annual_instances_assignee_id'), table_name='cipc_annual_instances')
    op.drop_table('cipc_annual_instances')
    # ### end Alembic commands ###
    # drop_table does not drop the native enum type; do it explicitly so a
    # downgrade → re-upgrade cycle doesn't fail on "type cipcannualstatus already exists".
    sa.Enum(name='cipcannualstatus').drop(op.get_bind(), checkfirst=True)
