"""add client allocation and CIPC anniversary fields

Revision ID: 6b03e634f495
Revises: 5fd5a3a5a26a
Create Date: 2026-06-03 09:49:22.365605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b03e634f495'
down_revision = '5fd5a3a5a26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('cipc_anniversary_month', sa.SmallInteger(), nullable=True))
    op.add_column('clients', sa.Column('cipc_anniversary_day', sa.SmallInteger(), nullable=True))
    op.add_column('clients', sa.Column('allocated_staff_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_clients_allocated_staff_id'), 'clients', ['allocated_staff_id'], unique=False)
    op.create_foreign_key(None, 'clients', 'staff', ['allocated_staff_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_index(op.f('ix_clients_allocated_staff_id'), table_name='clients')
    op.drop_column('clients', 'allocated_staff_id')
    op.drop_column('clients', 'cipc_anniversary_day')
    op.drop_column('clients', 'cipc_anniversary_month')
    # ### end Alembic commands ###
