"""add obligation_instances table

Revision ID: 6bee3e81960c
Revises: 6102eb116e8d
Create Date: 2026-05-12 17:55:05.860829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bee3e81960c'
down_revision = '6102eb116e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obligation_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('obligation_type', sa.Enum('VAT201', name='obligationtype'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('submission_due_date', sa.Date(), nullable=False),
    sa.Column('payment_due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', 'PAID', 'EXEMPT', name='obligationstatus'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'obligation_type', 'period_end', name='uq_obligation_instances_client_type_period')
    )
    with op.batch_alter_table('obligation_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_obligation_instances_client_id'), ['client_id'], unique=False)
        batch_op.create_index('ix_obligation_instances_status_submission_due', ['status', 'submission_due_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('obligation_instances', schema=None) as batch_op:
        batch_op.drop_index('ix_obligation_instances_status_submission_due')
        batch_op.drop_index(batch_op.f('ix_obligation_instances_client_id'))

    op.drop_table('obligation_instances')
    # ### end Alembic commands ###
