"""Add notes column to obligation_instances

Revision ID: 769c137467b0
Revises: 1009fb776132
Create Date: 2026-05-16 09:25:12.890229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769c137467b0'
down_revision = '1009fb776132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obligation_instances', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obligation_instances', 'notes')
    # ### end Alembic commands ###
