"""restructure client contact fields (structured address + cc_email)

Revision ID: 9766be8a3a42
Revises: 1f1ec8ef2984
Create Date: 2026-06-03 10:23:26.281104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9766be8a3a42'
down_revision = '1f1ec8ef2984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('cc_email', sa.String(length=200), nullable=True))
    op.add_column('clients', sa.Column('work_phone', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('fax', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('street1', sa.String(length=200), nullable=True))
    op.add_column('clients', sa.Column('street2', sa.String(length=200), nullable=True))
    op.add_column('clients', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('postcode', sa.String(length=20), nullable=True))
    op.drop_column('clients', 'postal_address')
    op.drop_column('clients', 'physical_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('physical_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('postal_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('clients', 'postcode')
    op.drop_column('clients', 'city')
    op.drop_column('clients', 'street2')
    op.drop_column('clients', 'street1')
    op.drop_column('clients', 'fax')
    op.drop_column('clients', 'work_phone')
    op.drop_column('clients', 'cc_email')
    # ### end Alembic commands ###
