"""create clients table

Revision ID: a1d8b9a7c82c
Revises: 
Create Date: 2026-05-11 12:48:17.376516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d8b9a7c82c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('trading_name', sa.String(length=200), nullable=True),
    sa.Column('entity_type', sa.Enum('INDIVIDUAL', 'SOLE_PROP', 'PTY_LTD', 'CC', 'TRUST', 'PARTNERSHIP', 'NPC', name='entitytype'), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('tax_ref', sa.String(length=50), nullable=True),
    sa.Column('vat_number', sa.String(length=50), nullable=True),
    sa.Column('paye_number', sa.String(length=50), nullable=True),
    sa.Column('year_end_month', sa.SmallInteger(), nullable=True),
    sa.Column('year_end_day', sa.SmallInteger(), nullable=True),
    sa.Column('bbee_applicable', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('client_since', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('has_income_tax', sa.Boolean(), nullable=False),
    sa.Column('has_vat', sa.Boolean(), nullable=False),
    sa.Column('has_paye', sa.Boolean(), nullable=False),
    sa.Column('has_provisional_tax', sa.Boolean(), nullable=False),
    sa.Column('has_dividends_tax', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
